queries:
  - exclude: cpp/potentially-dangerous-function
extraction:
  python:
    python_setup: 
      version: 3
      requirements_files: 
        - tools/python/requirements.txt
      setup_py: false
