path_classifiers:
  3rdparty:
    - exclude: 3rdparty
queries:
  - exclude: cpp/potentially-dangerous-function
extraction:
  cpp:
    after_prepare:
      - cd 3rdparty/boost && ./bootstrap.sh && ./b2
  python:
    python_setup: 
      version: 3
      requirements_files: 
        - tools/python/requirements.txt
      setup_py: false
