language: cpp
dist: trusty
sudo: false

matrix:
  include:
    - os: linux
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-5
      env:
         - MATRIX_EVAL="CC=gcc-5 && CXX=g++-5"
      script:
         - mkdir cbuild
         - cd cbuild
         - cmake -G "Unix Makefiles" ..
         - make || travis_terminate 1

before_install:
    - eval "${MATRIX_EVAL}"

before_script:
  - uname -a
  - ./tools/ci/sql.sh

script:
  - ./tools/ci/npc.sh
  - ./login-server --run-once
  - ./char-server --run-once
  - ./map-server --run-once

env:
  global:
    - DB_ROOT="root"
    - DB_HOST="127.0.0.1"
    - DB_NAME="ragnarok"
    - DB_USER="ragnarok"
    - DB_PASS="ragnarok"

notifications:
  email: false
