language: cpp
dist: trusty
sudo: false

matrix:
  include:
    - os: linux
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-5
      env:
         - MATRIX_EVAL="CC=gcc-5 && CXX=g++-5"

before_install:
    - eval "${MATRIX_EVAL}"
    - cd 3rdparty/boost && ./bootstrap.sh && ./b2
    - cd $TRAVIS_BUILD_DIR

before_script:
  - uname -a
  - ./tools/ci/sql.sh

script:
  - ./tools/ci/npc.sh
  - mkdir cbuild || travis_terminate 1
  - cd cbuild || travis_terminate 1
  - cmake -G "Unix Makefiles" .. || travis_terminate 1
  - make || travis_terminate 1
  - cd $TRAVIS_BUILD_DIR || travis_terminate 1
  - ./login-server --run-once
  - ./char-server --run-once
  - ./map-server --run-once

env:
  global:
    - DB_ROOT="root"
    - DB_HOST="127.0.0.1"
    - DB_NAME="ragnarok"
    - DB_USER="ragnarok"
    - DB_PASS="ragnarok"

notifications:
  email: false
