blank_issues_enabled: false
contact_links:
  - name: Discord 服务器
    about: "加入我们的 Discord 服务器与同好们一起交流吧!"
    url: https://discord.gg/9bEfrPPruj
    
  - name: QQ 爱好者交流群
    about: "熊猫模拟器的交流 QQ 群号是: 928171346，欢迎来访!"
    url: https://jq.qq.com/?_wv=1027&k=kCf9d71M
