@echo off

mysql --host %DB_HOST% -u %DB_ROOT% -e "CREATE DATABASE %DB_NAME%;"
mysql --host %DB_HOST% -u %DB_ROOT% %DB_NAME% -e "source sql-files\main.sql"
mysql --host %DB_HOST% -u %DB_ROOT% %DB_NAME% -e "source sql-files\logs.sql"
mysql --host %DB_HOST% -u %DB_ROOT% %DB_NAME% -e "source sql-files\item_db.sql"
mysql --host %DB_HOST% -u %DB_ROOT% %DB_NAME% -e "source sql-files\item_db_usable.sql"
mysql --host %DB_HOST% -u %DB_ROOT% %DB_NAME% -e "source sql-files\item_db_equip.sql"
mysql --host %DB_HOST% -u %DB_ROOT% %DB_NAME% -e "source sql-files\item_db_etc.sql"
mysql --host %DB_HOST% -u %DB_ROOT% %DB_NAME% -e "source sql-files\item_db2.sql"
mysql --host %DB_HOST% -u %DB_ROOT% %DB_NAME% -e "source sql-files\item_db_re.sql"
mysql --host %DB_HOST% -u %DB_ROOT% %DB_NAME% -e "source sql-files\item_db_re_usable.sql"
mysql --host %DB_HOST% -u %DB_ROOT% %DB_NAME% -e "source sql-files\item_db_re_equip.sql"
mysql --host %DB_HOST% -u %DB_ROOT% %DB_NAME% -e "source sql-files\item_db_re_etc.sql"
mysql --host %DB_HOST% -u %DB_ROOT% %DB_NAME% -e "source sql-files\item_db2_re.sql"
mysql --host %DB_HOST% -u %DB_ROOT% %DB_NAME% -e "source sql-files\mob_db.sql"
mysql --host %DB_HOST% -u %DB_ROOT% %DB_NAME% -e "source sql-files\mob_db2.sql"
mysql --host %DB_HOST% -u %DB_ROOT% %DB_NAME% -e "source sql-files\mob_db_re.sql"
mysql --host %DB_HOST% -u %DB_ROOT% %DB_NAME% -e "source sql-files\mob_db2_re.sql"
mysql --host %DB_HOST% -u %DB_ROOT% %DB_NAME% -e "source sql-files\mob_skill_db.sql"
mysql --host %DB_HOST% -u %DB_ROOT% %DB_NAME% -e "source sql-files\mob_skill_db2.sql"
mysql --host %DB_HOST% -u %DB_ROOT% %DB_NAME% -e "source sql-files\mob_skill_db_re.sql"
mysql --host %DB_HOST% -u %DB_ROOT% %DB_NAME% -e "source sql-files\mob_skill_db2_re.sql"
mysql --host %DB_HOST% -u %DB_ROOT% %DB_NAME% -e "source sql-files\roulette_default_data.sql"

mysql --host %DB_HOST% -u %DB_ROOT% -e "CREATE USER '%DB_USER%'@'%%' IDENTIFIED WITH mysql_native_password BY '%DB_PASS%';"
mysql --host %DB_HOST% -u %DB_ROOT% -e "GRANT ALL PRIVILEGES ON %DB_NAME%.* TO'%DB_USER%'@'%%';"
